Better error message for out of bound eps
ibpsa/modelica-ibpsa pull request #1444
Opened 2021-02-03 18:22 UTC by bravache

Originally this change was only to fix the calculation in the error message, but looking further into it, I also figured that the `abs` is redundant in the calculation of `eps_nominal`.

Reasoning: Without the `abs`, you could rewrite the `eps_nominal` equation like so (just by refactoring the equation without assuming any other existing physical equalities):
```
if CMin_flow_nominal == C1_flow_nominal:
    eps_nominal = C2_flow_nominal / C1_flow_nominal * (T_b2_nominal - T_a2_nominal) / (T_a1_nominal - T_a2_nominal)
else:
    eps_nominal = (T_b2_nominal - T_a2_nominal) / (T_a1_nominal - T_a2_nominal)
```

The factor `C2_flow_nominal / C1_flow_nominal` is positive and enforced by `assert` statements on line 87 and 90, which verify that both nominal flow rates are positive.

The factor `(T_b2_nominal - T_a2_nominal) / (T_a1_nominal - T_a2_nominal)` is always be positive when the user selected nominal values are right: side 2 is heating up (b2 >= a2) if and only if side 1 comes in hotter (a1 >= a2). If the values are wrong, then the following `assert` statement would catch it (`eps_nominal < 0`).

2021-02-05 22:25 UTC, AntoineGautier requested changes
The modified model needs a revision note.

It is also a non-backward compatible change.
And I don't see an easy conversion script to automate the refactoring.
The issue is that `Q_flow_nominal` is only loosely defined by its description string `Nominal heat transfer`. In the code it is clear that it is the heat transfer from 1 to 2.
https://github.com/ibpsa/modelica-ibpsa/blob/d1ee2f415d443f60437bf609840afbfa2dfcb829/IBPSA/Fluid/HeatExchangers/BaseClasses/PartialEffectivenessNTU.mo#L97-L103 

However, the model is fully reversible and more often than not users configure it with side 2 being the source and side 1 the load (don't ask me why).
So the change proposed here will trigger this kind of error (as in `Buildings.Examples.VAVReheat.ASHRAE2006`) in number.
```
Error: The following error was detected at time: 0
  eps_nominal out of bounds, eps_nominal = -0.504117
  To achieve the required heat transfer rate at epsilon=0.8, set T_a1_nominal-T_a2_nominal = 41.2746
  or increase flow rates. The current parameters result in 
  CMin_flow_nominal = 5474.46
  CMax_flow_nominal = 17739
  Failed condition: cor.terHea.eps_nominal > 0 and cor.terHea.eps_nominal < 1
```
If we agree on it, we should at least modify the description string of `Q_flow_nominal`, perhaps catch the 2nd Law violation with a specific and more explicit assert statement, and think if there is a conversion script that can be developed for Dymola users at least.

2021-02-08 16:01 UTC, mwetter commented
I don't quite see what the benefit is of avoiding the `abs()` value and having a bit a shorter expression but at the cost of a backward incompatible change that affects many models. This equation is only evaluated once in the initial equation section (but not during the simulation) and therefore there would be no change in computing time. Is there any other more important benefit that I miss?

2021-02-08 16:58 UTC, bravache commented
> I don't quite see what the benefit is of avoiding the `abs()` value and having a bit a shorter expression but at the cost of a backward incompatible change that affects many models. This equation is only evaluated once in the initial equation section (but not during the simulation) and therefore there would be no change in computing time. Is there any other more important benefit that I miss?

@mwetter I originally did not catch that it would not be backward compatible, but Antoine showed me that the convention on the direction of `Q_nominal_flow` was not enforced, and therefore can have the wrong sign. Given that, I guess it's a small change that we could drop, although we should still fix the error message.
If I were to argue on why we should go forward with this breaking change:
- It would enforce the same convention for all heat exchanger, that `Q_flow_nominal` is the heat from port `*1` to `*2`, or in other words, that it is negative when `*1` is heating.
- It would prevent `T_b1_nominal` and `T_b2_nominal` from taking the wrong value. Right now, if a user input `Q_flow_nominal` with the wrong sign, the calculated outlet temperature of both port will be wrong, since the `deltaT` will be inversed. This is not critical since these values are apparently not used outside of that sizing calculation, but this could lead to confusion.
- Future code might rely on an assumed convention of `Q_flow_nominal` or rely on the nominal outlet temperatures, and this tech debt would come in the way.

2021-02-08 20:50 UTC, bravache commented
@mwetter @AntoineGautier Following our meeting conversation, I have reverted the changes in this branch to only include the fix to the error message. I am opening another PR for raising a DeprecationWarning and updating `Q_flow_nominal` description.

2021-02-09 13:16 UTC, mwetter commented
@Mathadon : Can you please review and merge if you agree (wrong equation in message of assertion).

2021-02-09 13:18 UTC, Mathadon approved these changes

2021-02-09 14:39 UTC, Mathadon commented
I cannot merge since the PR has to be approved by @AntoineGautier

2021-02-09 16:50 UTC, AntoineGautier approved these changes

2021-02-10 16:15 UTC, merged