Issue1704 move nrpm mover to obsolete
ibpsa/modelica-ibpsa pull request #1717
Opened 2023-03-21 15:25 UTC by hcasperfu

This closes #1704.

Changes made in this PR:
- `Movers.SpeedControlled_Nrpm` and `Movers.Preconfigured.SpeedControlled_Nrpm` are moved to `Obsolete`.
- In the following models, any and all `_Nrpm` mover models are replaced with `_y` models.
  - `Validation.PowerSimplified`, and its extended models `PowerExact` and `PowerEuler`. The components on the canvas are also moved lower to make space.
  - `Validation.Pump_Nrpm_stratos`, and it is renamed as `Pump_y_stratos`.
  - `Validation.Pump_stratos`.
  - `Validation.PumpCurveDerivatives`.
- The model `Validation.SpeedControlled_Nrpm` is moved to `Obsolete`, because it specifically tests the `_Nrpm` model and a `_y` equivalent of it already exists.
- The following models are copied to `Obsolete`, and the `_Nrpm` mover in the original models is deleted:
  - Models that extend from `Validation.BaseClasses.ControlledFlowMachine`:
    - `Validation.ControlledFlowMachine`
    - `Validation.ControlledFlowMachineDynamic`
    - `Preconfigured.Validation.ControlledFlowMachinePreconfigured`
  - `Examples.MoverParameter`, and its extended models `MoverContinuous` and `MoverStages`.

2023-03-27 20:58 UTC, mwetter requested changes
Please see the inline comment. Also, please search for `rpm` in `IBPSA.Movers` as there are various references that should be removed. We should formulate the model and documentation without any reference to rpm as rpm is no longer used. Otherwise, users may think the rpm values have some relevance.

Also, links such as 
```
<a href=\"modelica://IBPSA.Fluid.Movers.FlowControlled_Nrpm\">
IBPSA.Fluid.Movers.FlowControlled_Nrpm</a>
```
need to be changed as this will lead to an invalid link in the generated html.

2023-03-27 20:58 UTC, mwetter commented on IBPSA/Obsolete/Fluid/Movers/SpeedControlled_Nrpm.mo
This model misses the `obsolete` annotation, see https://github.com/ibpsa/modelica-ibpsa/blob/040a3d1c09f9fa523d5fc518c3aa1b73e66de292/IBPSA/Obsolete/Fluid/FixedResistances/PlugFlowPipe.mo#L215

Without it, users won't get a warning.

Also, it needs to extend from `IBPSA.Obsolete.BaseClasses.ObsoleteModel`
https://github.com/ibpsa/modelica-ibpsa/blob/040a3d1c09f9fa523d5fc518c3aa1b73e66de292/IBPSA/Obsolete/Fluid/FixedResistances/PlugFlowPipe.mo#L3

2023-03-28 14:30 UTC, hcasperfu commented on IBPSA/Obsolete/Fluid/Movers/SpeedControlled_Nrpm.mo
Question: Once I mark the model with an obsolete annotation, some validation/example models that use this component no longer simulate. I see that the `Obsolete` package is not in IBPSA's CI tests. So do I just leave them broken?

2023-03-28 15:03 UTC, mwetter commented on IBPSA/Obsolete/Fluid/Movers/SpeedControlled_Nrpm.mo
@hcasperfu : Models marked as obsolete should still simulate and work in the CI tests (they do for `Buildings`). But you are right, `IBPSA/.travis.yml` does not include `IBPSA.Obsolete`. This is a mistake and it should be added.

2023-03-30 19:23 UTC, mwetter commented on IBPSA/Fluid/Movers/Data/Generic.mo
Looks good, except for one missed paragraph that I deleted in 0c17ba76c

2023-03-30 19:24 UTC, mwetter approved these changes

2023-03-30 19:25 UTC, mwetter commented
This is ready to merge, but we should have one non-LBNL reviewer.

@hcasperfu : can you please merge this downstream to the `Buildings` library `master` (not the `maint_9.1.x` branch).

2023-04-03 16:03 UTC, Mathadon approved these changes
that's a serious cleanup, thanks!

2023-04-04 13:28 UTC, merged