Declared variables on weather bus
ibpsa/modelica-ibpsa pull request #1799
Opened 2023-09-23 00:53 UTC by mwetter

This closes #1798

2023-09-28 12:08 UTC, mwetter commented
@jelgerjansen : This is ready for review. Can you please review as this will also make the tutorial more practical, see https://github.com/ibpsa/modelica-ibpsa/pull/1799/commits/395265eb35619af19af4816b2cb56d3c963919e2

2023-09-28 15:31 UTC, jelgerjansen requested changes
Very nice fix Michael, thanks!
I only have one small comment you can have a look at.
Furthermore, I wasn't able to reproduce the error message you mention [here](https://github.com/ibpsa/modelica-ibpsa/issues/1798#issue-1909644887) when opening the weather data reader itself or a model that contains the reader. When/where did you see this error appearing? (I used version OMEdit v1.21.0)

2023-09-28 15:55 UTC, mwetter commented on IBPSA/BoundaryConditions/WeatherData/Bus.mo
> +  Modelica.Units.SI.Temperature TDryBul(displayUnit="degC")
Thanks, I removed the `displayUnit`

2023-09-28 15:57 UTC, mwetter commented
@jelgerjansen : Regarding the error message, this is with 1.22.0~dev-351-g208d900, using `OMEdit --NAPI=true` which activates the new back-end that will soon be the default.

2023-09-29 11:36 UTC, jelgerjansen approved these changes

2023-09-29 13:04 UTC, merged