Issue1926 actuator travel
ibpsa/modelica-ibpsa pull request #1933
Opened 2024-09-15 23:26 UTC by mwetter

This closes #1926

2024-09-18 14:58 UTC, mwetter commented
This is ready for review and merge.
@jelgerjansen : Can you please review.
@nytschgeusen @FWuellhorst : Can you please give your OK within 2 weeks as this is a non-backward compatible change. The conversion script has been updated.

2024-09-19 13:16 UTC, jelgerjansen requested changes
@mwetter thank you for your nice work! Most of my feedback are minor comments. Two issues that might require some more time:

- I noticed that the renaming (conversion script) also changed variable names in the revision history, which is unintended. I'm not sure if this can be avoided somehow?
- The value of `Td` (in the `SlewRateLimiter`) is defined as `10/strokeTime`, but I would have expected `strokeTime` in the numerator (both in terms of units and physical meaning). Could you explain how you choose the expression for `Td`?

2024-09-19 13:16 UTC, jelgerjansen commented on IBPSA/Fluid/Movers/SpeedControlled_y.mo
> +        final etaMotMet=per.etaMotMet), r_N(start=y_start)));
Move `r_N(...` to new line to improve readability.

2024-09-19 13:16 UTC, jelgerjansen commented on IBPSA/Fluid/Movers/Validation/ComparePowerHydraulic.mo
> +      use_riseTime   =false),
Remove abundant whitespace after `use_riseTime`.

2024-09-19 13:16 UTC, jelgerjansen commented on IBPSA/Fluid/Movers/Validation/ComparePowerHydraulic.mo
> +      use_riseTime   =false),
Remove abundant whitespace after `use_riseTime`.

2024-09-19 13:16 UTC, jelgerjansen commented on IBPSA/Fluid/Movers/Validation/ComparePowerHydraulic.mo
> +      use_riseTime   =false));
Remove abundant whitespace after `use_riseTime`.

2024-09-19 13:16 UTC, jelgerjansen commented on IBPSA/Fluid/Movers/Validation/ComparePowerInput.mo
> +      use_riseTime   =false),
Remove abundant whitespace after `use_riseTime`.

2024-09-19 13:16 UTC, jelgerjansen commented on IBPSA/Fluid/Movers/Validation/ControlledFlowMachine.mo
> +      use_riseTime   =false));
Remove abundant whitespace after `use_riseTime`.

2024-09-19 13:16 UTC, jelgerjansen commented on IBPSA/Fluid/Movers/Validation/FlowControlled_dp.mo
> +      use_riseTime   =false));
Remove abundant whitespace after `use_riseTime`.

2024-09-19 13:16 UTC, jelgerjansen commented on IBPSA/Fluid/Movers/Validation/FlowControlled_m_flow.mo
> +      use_riseTime   =false));
Remove abundant whitespace after `use_riseTime`.

2024-09-19 13:16 UTC, jelgerjansen commented on IBPSA/Fluid/Movers/Validation/Pump_stratos.mo
> +      use_riseTime   =false));
Remove abundant whitespace after `use_riseTime`.

2024-09-19 13:16 UTC, jelgerjansen commented on IBPSA/Fluid/Movers/Validation/SpeedControlled_y.mo
> +      use_riseTime   =false));
Remove abundant whitespace after `use_riseTime`.

2024-09-19 21:54 UTC, mwetter commented on IBPSA/Fluid/Actuators/BaseClasses/ActuatorSignal.mo
> +    Td=10/strokeTime,
This is now corrected on this development branch through https://github.com/ibpsa/modelica-ibpsa/pull/1933/commits/1ac4b554d2ffed41651b18c40a7a5fabb08b4ff2

2024-09-20 21:13 UTC, mwetter commented on IBPSA/Electrical/Transmission/BaseClasses/BaseCable.mo
> +<li>
Corrected by adding both revision notes.

2024-09-20 21:17 UTC, mwetter commented on IBPSA/Fluid/Actuators/BaseClasses/ActuatorSignal.mo
> +This is for <a href=\"https://github.com/lbl-srg/modelica-buildings/issues/3965\">Buildings, #3965</a>.
Done, both are mentioned now.

2024-09-20 21:17 UTC, mwetter commented on IBPSA/Fluid/Actuators/BaseClasses/PartialThreeWayValve.mo
> +      res1 constrainedby IBPSA.Fluid.Actuators.BaseClasses.PartialTwoWayValve(
Done.

2024-09-20 21:17 UTC, mwetter commented on IBPSA/Fluid/Movers/Validation/ControlledFlowMachine.mo
> +      use_riseTime   =false));
Done.

2024-09-20 21:22 UTC, mwetter commented
@FWuellhorst : Thanks for the review. All changes have been addressed.

2024-09-23 12:42 UTC, jelgerjansen commented on IBPSA/Fluid/Actuators/BaseClasses/ActuatorSignal.mo
> +This is for <a href=\"https://github.com/lbl-srg/modelica-buildings/issues/3965\">Buildings, #3965</a>.
I noticed an abundant whitespace before the IBPSA hyperlink, which I fixed through commit 27c8c85

2024-09-23 12:48 UTC, jelgerjansen commented
@mwetter I think you indeed mixed up the names of @FWuellhorst and myself ;)

Thanks for fixing the time constant of the SlewRateLimiter block. Did this lead to significant changes in simulation time and/or results?

The updated revision notes contained an abundant white space, which I fixed myself through commit 27c8c85.

Furthermore, I noticed that some of my remarks were not yet addressed. Did you read over these comments or do you prefer the implementation as is?

2024-09-23 17:53 UTC, mwetter commented on IBPSA/Fluid/Actuators/BaseClasses/ActuatorSignal.mo
> -  IBPSA.Fluid.BaseClasses.ActuatorFilter filter(
Let's move it through a separate PR. I opened https://github.com/ibpsa/modelica-ibpsa

2024-09-23 18:04 UTC, mwetter commented
@jelgerjansen : Sorry for missing some comments, I thought I addressed them through the text replace.

The simulation time stays about the same, some models become faster and others slower, see the link in the issue. In `Buildings` we have some models that don't work and we are looking into this, the reason being pump working against a closed valve and some chattering in control logic. I think it is not fundamental to this change but rather a change in numerics that now needs retuning or reformulation of some models that we got to work for the old filter model. I would expect a similar change being needed if models would have been developed for the new SlewRateLimiter and we were to change to the 2nd order filter.

2024-09-24 09:39 UTC, jelgerjansen commented
@mwetter thanks for addressing the other comments as well. I think this is now ready to be merged.

2024-09-24 09:39 UTC, jelgerjansen approved these changes

2024-10-08 15:36 UTC, merged